// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package testdata

import (
	"context"
	"github.com/ONSdigital/dp-file-downloader/table"
	"net/http"
	"sync"
)

// Ensure, that RendererClientMock does implement table.RendererClient.
// If this is not the case, regenerate this file with moq.
var _ table.RendererClient = &RendererClientMock{}

// RendererClientMock is a mock implementation of table.RendererClient.
//
//	func TestSomethingThatUsesRendererClient(t *testing.T) {
//
//		// make and configure a mocked table.RendererClient
//		mockedRendererClient := &RendererClientMock{
//			PostBodyFunc: func(ctx context.Context, format string, body []byte) (*http.Response, error) {
//				panic("mock out the PostBody method")
//			},
//		}
//
//		// use mockedRendererClient in code that requires table.RendererClient
//		// and then make assertions.
//
//	}
type RendererClientMock struct {
	// PostBodyFunc mocks the PostBody method.
	PostBodyFunc func(ctx context.Context, format string, body []byte) (*http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// PostBody holds details about calls to the PostBody method.
		PostBody []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Format is the format argument value.
			Format string
			// Body is the body argument value.
			Body []byte
		}
	}
	lockPostBody sync.RWMutex
}

// PostBody calls PostBodyFunc.
func (mock *RendererClientMock) PostBody(ctx context.Context, format string, body []byte) (*http.Response, error) {
	if mock.PostBodyFunc == nil {
		panic("RendererClientMock.PostBodyFunc: method is nil but RendererClient.PostBody was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Format string
		Body   []byte
	}{
		Ctx:    ctx,
		Format: format,
		Body:   body,
	}
	mock.lockPostBody.Lock()
	mock.calls.PostBody = append(mock.calls.PostBody, callInfo)
	mock.lockPostBody.Unlock()
	return mock.PostBodyFunc(ctx, format, body)
}

// PostBodyCalls gets all the calls that were made to PostBody.
// Check the length with:
//
//	len(mockedRendererClient.PostBodyCalls())
func (mock *RendererClientMock) PostBodyCalls() []struct {
	Ctx    context.Context
	Format string
	Body   []byte
} {
	var calls []struct {
		Ctx    context.Context
		Format string
		Body   []byte
	}
	mock.lockPostBody.RLock()
	calls = mock.calls.PostBody
	mock.lockPostBody.RUnlock()
	return calls
}
