---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9.4

inputs:
  - name: dp-file-downloader
    path: go/src/github.com/ONSdigital/dp-file-downloader

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-file-downloader/ci/scripts/build.sh
