---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15.2

inputs:
  - name: dp-file-downloader

outputs:
  - name: build

run:
  path: dp-file-downloader/ci/scripts/audit.sh
